### ISSUE TITLE
Formato da data na impressão

### ISSUE THREAD

**Issue by rogeriolino** [novosga/triagem-touch#14]
Acertar formatação da data ao imprimir senha.

http://forum.novosga.org/discussion/294/formato-de-data-e-hora-impressao-senha

**Comment by thomasca1** [comment]
Desculpa sou novo... pode dar mais detalhes

**Comment by somatorio** [comment]
ok, mas o layout da impressão no triagem touch (v 1.3.0) continua diferente da impressão na triagem no novosga (v 1.4.0)

novosga:
![triagem](https://cloud.githubusercontent.com/assets/7087238/8359379/4d9e72fe-1b3c-11e5-8ad1-2cb72f4b981c.png)
triagem touch:
![triagem-touch](https://cloud.githubusercontent.com/assets/7087238/8359380/4d9f672c-1b3c-11e5-8af7-46d25b934adf.png)
