### ISSUE TITLE
No consigo contectar traigem-touch

### ISSUE THREAD

**Issue by agsbenitez** [novosga/triagem-touch#18]
Hola no he podido conectar triagem-touch
y no he encontrado documentación alguna.

estoy colocando los siguientes datos y no funciona

url: http://URL_SERVER//novosga/public/
unidade: solo mustra "Selecione"
usuario: ALGUN_USUARIO
Senha: SENHA

clien id: no se que poner
client secret: no se que poner

**Comment by rogeriolino** [comment]
Duplicado #19
