### ISSUE TITLE
Credenciais

### ISSUE THREAD

**Issue by hugoc09** [novosga/triagem-touch#19]
Na parte de Configuração, o que eu preencho nos campos: URL, Unidade, Usuário, Senha, Client id e Cliente secret.

Como faço pra levantar o código?

**Comment by rogeriolino** [comment]
URL é a URL do NovoSGA (aplicação principal, PHP).

A Unidade irá carregar automaticamente caso a URL esteja correta.

Usuário e senha, são informações de um usuário do sistema que ficará como o emissor da senha. Por questão de segurança é melhor criar um usuário próprio para a triagem-touch.

Cient ID e Client secret são cadastrados na administração do Novo SGA, na parte de Web API. Os informações que restringem acesso a poder emitir senha via uma aplicação externa.
