### ISSUE TITLE
Senha para Acesso a Configuração do Triagem-Touch

### ISSUE THREAD

**Issue by paulocuiaba** [novosga/triagem-touch#20]
Sugiro a criação de uma senha para acesso a configuração do triagem touch e para tirar do fullscreen via tela de toque. Utilizando em nossa loja já tivemos problemas de pessoas alterando as configurações da tela o que impedia o uso correto (mesmo o navegador configurado como kiosk. Seria bom após 5 segundos sem digitar a senha para acesso, retorna para a seleção do serviço./emissão de senha, como acontece quando não se seleciona qual o tipo de atendimento.

**Comment by rogeriolino** [comment]
Paulo no código do master fiz uma modificação para poder customizar a exibição dos serviços e também escolher um botão para bloquear/desbloquear o menu:

https://github.com/novosga/triagem-touch/commit/55f2e4cbb86a219cfe1b01dd0f86bc08040f9d2b
