### ISSUE TITLE
[Melhoria] Posibilidade de Selecionar mais que uma Unidade

### ISSUE THREAD

**Issue by jppcel** [novosga/triagem-touch#24]
Seria interessante ter a opção de ter mais de uma unidade para que seja possível a criação de senhas para mais que uma unidade, visto a possibilidade por exemplo, de uso em uma prefeitura onde um mesmo totem pode ser compartilhado com 2 ou mais secretarias e assim, tendo esta necessidade.

**Comment by rogeriolino** [comment]
Na versão 2.0 foi adicionado Departamento, aonde você pode agrupar os serviços por departamento.

**Comment by jppcel** [comment]
No caso, a ideia é que haja a possibilidade de que cada secretaria tenha acesso aos itens de sua secretaria (Configurações, Relatórios e etc), por isso que o ideal é ter essa opção de seleção de mais que uma unidade.

**Comment by rogeriolino** [comment]
Entendi. No caso então você precisa de um agregador de triagem, não vejo como funcionalidade desse projeto, talvez como um outro específico para atender esta necessidade.

**Comment by jppcel** [comment]
No caso desenvolvi uma tela para isso usando Angular para web [timcr/novosga-totem](https://github.com/timcr/novosga-totem), mas seria bom fazer isso na versão geral.
