### ISSUE TITLE
Não consigo imprimir - Triagem Touch - erro cross-origin

### ISSUE THREAD

**Issue by csi-sfiemt** [novosga/triagem-touch#25]
Fiz todas as instalações no Novo SGA, Painel Web e Triagem Touch, mas ao gerar uma senha no Triagem Touch ocorre um erro de permissão "cross-origin" e a impressão não é realizada.

A mensagem é: SecurityError: Permission denied to access property "print" on cross-origin object

Isso ocorre em todos os navegadores, Firefox, Chrome e Edge.

O que é necessário configurar ou liberar para que a impressão funcione?

Um print do erro está aqui: https://ibb.co/cQvwm9

Instalei tudo ontem, então as versões estão todas atualizadas.

Ambiente
- Linux Debian 9 Stretch
- PHP 7.1.22
- MySQL 5.7
- Apache 2.4.25
- Novo SGA v2.0.3

**Comment by rogeriolino** [comment]
A triagem-touch v2 foi desenvolvida para ser executada nativamente, via Electron. Esse problema está ocorrendo porque você está usando pelo navegador.

**Comment by csi-sfiemt** [comment]
Rogério

Obrigado pelo esclarecimento, eu li o manual e não consegui distinguir essa diferença, por não conhecer Vue e o Electron não consegui identificar claramente que existia um build para Web e um App Electron. Há pouco consegui fazer o build do App e funcionou a impressão.

Obrigado pelo esclarecimento.

**Comment by rogeriolino** [comment]
De nada. A documentação está zero mesmo. Por isso quando gerei a release coloquei os builds prontos, tanto AppImage quanto exe.

**Comment by paa-listas** [comment]
I have the some problem with de web compilation. Will be provided a solution for this 'cross-origin' error, I also need the Web UI? Thanks in advance.

**Comment by sidneybs1** [comment]
Olá, bom dia.
estou tendo problema na triagem-touch,
fiz toda a configuração necessária e não funciona, da o seguinte erro:
![debug do erro](https://user-images.githubusercontent.com/40635786/52067497-0f40e280-2551-11e9-9151-103cc42be219.png)
veja a configuração:
![tela admin web api](https://user-images.githubusercontent.com/40635786/52067647-6e065c00-2551-11e9-81de-766572daf48a.png)
![configuracao triagem-touch](https://user-images.githubusercontent.com/40635786/52067671-7eb6d200-2551-11e9-8e82-f3a7e6edece8.png)

**Comment by sidneybs1** [comment]
não sei mais o que faser, preciso ativar a funão touch e não estou conseguindo, por favor alguem pode me ajudar?

**Comment by paa-listas** [comment]
Mmm this thread is for Novo SGA 2.0. Are you using Novo SGA 1.5?
