### ISSUE TITLE
Imprimir o local de atendimento na senha

### ISSUE THREAD

**Issue by christiantosta** [novosga/triagem-touch#3]
É importante que se imprima o local do atendimento na senha.

**Comment by geraldorodrigues** [comment]
Olá, poderia me informar como inserir o local do atendimento no NovoSGA 1.5 ?

**Comment by wendelmeloo** [comment]
> Com o lançamento da versão v1.3.0 do Novo SGA foi possível unificar o layout de impressão. Então agora não existe mais arquivo de impressão local do Triagem Touch. E toda a alteração de layout de impressão deve ser feita no lado do servidor.

Olá, poderia me informar como inserir o local do atendimento no NovoSGA 1.5 ?
