### ISSUE TITLE
Visualizar Local e outras configurações no Triagem-Touch

### ISSUE THREAD

**Issue by paulocuiaba** [novosga/triagem-touch#7]
Boa tarde, 

Creio que seria interessante ter na tela do Triagem-touch o nome do local bem como mais opções para personalização como imagem de fundo e cores.

Atenciosamente, 
##

**Comment by rogeriolino** [comment]
Paulo, mesma situação do issue #20, no master tem uma opção de customizar o título e subtítulo nas configurações.
